# Generated by Django 3.2.9 on 2021-11-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='remaining_balance',
            field=models.FloatField(default=50.0),
        ),
    ]
