# Generated by Django 3.2.9 on 2021-11-21 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setup',
        ),
    ]
