# Generated by Django 3.2.9 on 2021-11-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0002_alter_receipt_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='photo',
            field=models.CharField(max_length=256),
        ),
    ]
