# Generated by Django 3.2.9 on 2021-11-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0003_alter_receipt_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='slug',
            field=models.SlugField(blank=True, max_length=70),
        ),
    ]
