# Generated by Django 3.2.9 on 2021-11-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0004_receipt_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='slug',
        ),
        migrations.AddField(
            model_name='receipt',
            name='proceed',
            field=models.BooleanField(default=False),
        ),
    ]
